import { Copy, User, Users, MessageCircle, Award, Shield, Zap } from "lucide-react";

export const brandIdentity = {
  name: "ASCEND: FITNESS RPG",
  tagline: "Turn Workouts into Epic Quests",
  shortTagline: "Level Up Your Fitness",
  
  description: "ASCEND transforms your workouts into epic quests. Earn XP, level up, and climb to hunter rankings. Train solo or compete with hunters worldwide.",
  
  valueProposition: [
    {
      title: "AI-Powered Quests",
      description: "Personalized workouts generated by Groq AI based on your goals and preferences.",
      icon: Zap,
      color: "text-system-cyan",
    },
    {
      title: "Gamification",
      description: "Earn XP, level up, and achieve hunter ranks from E to S. Unlock achievements and special classes.",
      icon: Award,
      color: "text-purple-400",
    },
    {
      title: "Social Community",
      description: "Join Hunter Network feed, climb leaderboards, and connect with hunters worldwide.",
      icon: Users,
      color: "text-blue-400",
    },
    {
      title: "Verification System",
      description: "Upload proof of completion. Anti-cheat system ensures fair competition.",
      icon: Shield,
      color: "text-green-400",
    },
    {
      title: "Real-time Feedback",
      description: "Opik AI judge evaluates your performance and provides instant feedback.",
      icon: MessageCircle,
      color: "text-yellow-400",
    },
  ],

  voice: {
    tone: "Epic, motivational, gamified",
    language: "Hunter/quest terminology",
    personality: "Encouraging, challenging, supportive",
  },

  features: {
    hero: {
      title: "Turn Workouts into Epic Quests",
      subtitle: "Transform your fitness journey into an RPG adventure",
      cta: "Start Your Journey",
      secondaryCta: "Try Demo Accounts",
    },
    socialProof: {
      title: "Join Hunters Worldwide",
      subtitle: "Compete, collaborate, and climb the rankings",
    },
    howItWorks: {
      title: "How It Works",
      steps: [
        {
          id: 1,
          title: "Choose Your Class",
          description: "Select Tank, Striker, or Assassin class that fits your training style.",
          icon: User,
        },
        {
          id: 2,
          title: "Generate Quest",
          description: "AI generates personalized workouts based on your goals and equipment.",
          icon: Zap,
        },
        {
          id: 3,
          title: "Complete & Upload Proof",
          description: "Track exercises, complete your quest, and upload proof for verification.",
          icon: Copy,
        },
        {
          id: 4,
          title: "Get Ranked",
          description: "Earn XP, level up, and climb from E to S rank on the leaderboard.",
          icon: Award,
        },
      ],
    },
  },

  opikTransparency: {
    title: "Transparent AI Monitoring",
    description: "We use Opik to monitor app performance and improve your experience. Your privacy is our priority.",
    whatWeTrack: [
      "Quest generation requests",
      "AI judge evaluations",
      "Performance metrics",
      "Error tracking",
    ],
    whatWeDontTrack: [
      "Personal workout data",
      "User conversations",
      "Biometric data",
      "Private information",
    ],
    learnMore: "Learn About Opik Monitoring",
  },

  demoAccounts: {
    title: "Try Demo Accounts",
    description: "Experience ASCEND with pre-configured hunter accounts at different rank levels.",
    cta: "View Demo Accounts",
    ranks: ["S-Rank", "A-Rank", "B-Rank", "C-Rank"],
    password: "Test123!",
  },

  cta: {
    primary: {
      title: "Ready to Start Your Journey?",
      description: "Join thousands of hunters leveling up their fitness one quest at a time.",
      button: "Get Started Free",
      secondaryButton: "Learn More",
    },
  },
};

export const landingSections = {
  hero: {
    id: "hero",
    title: "Turn Workouts into Epic Quests",
    subtitle: "ASCEND transforms your fitness journey into an RPG adventure. Earn XP, level up, and climb hunter rankings.",
    cta: "Start Your Journey",
    secondaryCta: "Try Demo Accounts",
  },

  features: {
    id: "features",
    title: "Features",
    subtitle: "Everything you need to gamify your fitness journey",
    cards: [
      {
        title: "AI-Powered Quests",
        description: "Personalized workouts generated by Groq AI based on your goals and preferences.",
        icon: Zap,
        color: "system-cyan",
      },
      {
        title: "Gamification",
        description: "Earn XP, level up, and achieve hunter ranks from E to S. Unlock achievements and special classes.",
        icon: Award,
        color: "purple-400",
      },
      {
        title: "Social Community",
        description: "Join Hunter Network feed, climb leaderboards, and connect with hunters worldwide.",
        icon: Users,
        color: "blue-400",
      },
      {
        title: "Verification System",
        description: "Upload proof of completion. Anti-cheat system ensures fair competition.",
        icon: Shield,
        color: "green-400",
      },
      {
        title: "Real-time Feedback",
        description: "Opik AI judge evaluates your performance and provides instant feedback.",
        icon: MessageCircle,
        color: "yellow-400",
      },
      {
        title: "Multi-Class System",
        description: "Choose Tank, Striker, or Assassin class that fits your training style.",
        icon: User,
        color: "pink-400",
      },
    ],
  },

  howItWorks: {
    id: "how-it-works",
    title: "How It Works",
    subtitle: "Start your fitness RPG journey in 4 simple steps",
    steps: [
      {
        id: 1,
        title: "Choose Your Class",
        description: "Select Tank, Striker, or Assassin class that fits your training style.",
        icon: User,
      },
      {
        id: 2,
        title: "Generate Quest",
        description: "AI generates personalized workouts based on your goals and equipment.",
        icon: Zap,
      },
      {
        id: 3,
        title: "Complete & Upload Proof",
        description: "Track exercises, complete your quest, and upload proof for verification.",
        icon: Copy,
      },
      {
        id: 4,
        title: "Get Ranked",
        description: "Earn XP, level up, and climb from E to S rank on the leaderboard.",
        icon: Award,
      },
    ],
  },

  demoAccounts: {
    id: "demo-accounts",
    title: "Try Demo Accounts",
    description: "Experience ASCEND with pre-configured hunter accounts at different rank levels.",
    cta: "View Demo Accounts",
    highlight: "All demo accounts use password: Test123!",
    ranks: [
      { rank: "S", count: 2, description: "Top-tier hunters with 90+ levels" },
      { rank: "A", count: 6, description: "Advanced hunters with 70+ levels" },
      { rank: "B", count: 8, description: "Experienced hunters with 40+ levels" },
      { rank: "C", count: 8, description: "Intermediate hunters with 10+ levels" },
    ],
  },

  opikTransparency: {
    id: "opik-transparency",
    title: "Transparent AI Monitoring",
    description: "We use Opik to monitor app performance and improve your experience. Your privacy is our priority.",
    whatWeTrack: [
      "Quest generation requests",
      "AI judge evaluations",
      "Performance metrics",
      "Error tracking",
    ],
    whatWeDontTrack: [
      "Personal workout data",
      "User conversations",
      "Biometric data",
      "Private information",
    ],
    learnMore: "Learn About Opik Monitoring",
    link: "/help/opik",
  },

  finalCta: {
    id: "cta",
    title: "Ready to Start Your Journey?",
    description: "Join thousands of hunters leveling up their fitness one quest at a time.",
    primaryButton: "Get Started Free",
    secondaryButton: "Learn More",
  },
};

export const socialProof = {
  title: "Trusted by Hunters Worldwide",
  stats: [
    {
      value: "10K+",
      label: "Active Hunters",
      icon: Users,
    },
    {
      value: "50K+",
      label: "Quests Completed",
      icon: Award,
    },
    {
      value: "500K+",
      label: "XP Earned",
      icon: Zap,
    },
    {
      value: "4.8",
      label: "App Rating",
      icon: Shield,
    },
  ],
};

export const testimonials = [
  {
    username: "ShadowHunter",
    rank: "S",
    content: "ASCEND completely transformed how I approach fitness. The gamification keeps me motivated, and the social features make me feel connected to a community.",
  },
  {
    username: "IronTank",
    rank: "A",
    content: "The AI-generated quests are incredibly personalized. It's like having a personal trainer that knows exactly what I need. The anti-cheat system ensures fair competition.",
  },
  {
    username: "SwiftNinja",
    rank: "C",
    content: "Started as a complete beginner. The quest system made learning proper form fun and rewarding. Now I'm climbing to B-Rank and loving every quest!",
  },
];
