export interface Feature {
  id: string;
  name: string;
  description: string;
  status: 'Planned' | 'In Progress' | 'Implemented';
  priority: 'High' | 'Medium' | 'Low';
  timeline: string;
  category: 'Core' | 'Social' | 'AI' | 'Monetization' | 'Innovation';
  starRating?: number;
}

export const roadmapFeatures: Feature[] = [
  {
    id: 'hunter-network',
    name: 'Hunter Network',
    description: 'Social feed with workout posts, kudos, respects, and following - Currently in demo mode',
    status: 'In Progress',
    priority: 'High',
    timeline: 'Q1 2026 (January-March)',
    category: 'Social',
  },
  {
    id: 'cost-planning',
    name: 'Cost Planning',
    description: 'Proactive cost management, monitoring, optimization, and ML-based predictions for profitable scaling',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q2 2026 (April-June)',
    category: 'Monetization',
    starRating: 4.5,
  },
  {
    id: 'help-system-completion',
    name: 'Complete Help System',
    description: 'Finish UI/UX tutorial, features documentation, and FAQ pages',
    status: 'Implemented',
    priority: 'High',
    timeline: 'Q2 2026 (April-June)',
    category: 'Core',
  },
  {
    id: 'gitbook-documentation',
    name: 'GitBook Documentation',
    description: 'Create comprehensive technical documentation with Opik integration evidence',
    status: 'Implemented',
    priority: 'High',
    timeline: 'Q2 2026 (April-June)',
    category: 'Core',
  },
  {
    id: 'navigation-integration',
    name: 'Navigation Integration',
    description: 'Add Help, Roadmap, and Tracker links to all navigation components',
    status: 'Implemented',
    priority: 'High',
    timeline: 'Q2 2026 (April-June)',
    category: 'Core',
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot',
    description: 'Interactive chatbot for exercise explanations, form corrections, and workout guidance',
    status: 'Planned',
    priority: 'High',
    timeline: 'Q3 2026 (July-September)',
    category: 'AI',
    starRating: 5,
  },
  {
    id: 'nutrition-tracking',
    name: 'Nutrition Tracking',
    description: 'Track meals, macros, and calories with AI macro estimation from food photos',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q3 2026 (July-September)',
    category: 'Core',
    starRating: 4.5,
  },
  {
    id: 'iot-scale-tracking',
    name: 'IoT Scale Tracking',
    description: 'Bluetooth scale integration, supplement tracking, body composition monitoring',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q3 2026 (July-September)',
    category: 'Innovation',
    starRating: 5,
  },
  {
    id: 'gym-tools-integration',
    name: 'Gym Tools Integration',
    description: 'Integrate with Technogym, Peloton, iFit, Echelon, and other gym equipment',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q3 2026 (July-September)',
    category: 'Innovation',
    starRating: 5,
  },
  {
    id: 'better-stats-tracker',
    name: 'Better Stats Tracker',
    description: 'GitHub-style progress graphs, detailed analytics, historical data visualization',
    status: 'Planned',
    priority: 'High',
    timeline: 'Q3 2026 (July-September)',
    category: 'Core',
    starRating: 5,
  },
  {
    id: 'social-media-integration',
    name: 'Social Media Integration',
    description: 'Share workouts to Instagram, TikTok, Twitter/X, Strava',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q3 2026 (July-September)',
    category: 'Social',
    starRating: 5,
  },
  {
    id: 'computer-vision',
    name: 'Computer Vision Integration',
    description: 'Real-time workout form evaluation using Clarifai (photos) and Replicate (video) with pose estimation and rep counting',
    status: 'Planned',
    priority: 'High',
    timeline: 'Q3 2026 (July-September)',
    category: 'AI',
  },
  {
    id: 'custom-workout-builder',
    name: 'Custom Workout Builder',
    description: 'Full control over workouts, exercise database, drag-and-drop builder',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q4 2026 (October-December)',
    category: 'Core',
    starRating: 5,
  },
  {
    id: 'guild-features',
    name: 'Guild Features',
    description: 'Guilds, dungeons, raids, boss battles, territory wars, team competitions',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q4 2026 (October-December)',
    category: 'Social',
    starRating: 5,
  },
  {
    id: 'monetization-system',
    name: 'Monetization System',
    description: 'Free/Pro tiers with different features, pricing plans, and exclusive Pro benefits',
    status: 'Planned',
    priority: 'Low',
    timeline: 'Q4 2026 (October-December)',
    category: 'Monetization',
    starRating: 5,
  },
  {
    id: 'leaderboard-2-0',
    name: 'Leaderboard 2.0',
    description: 'Multi-category leaderboards, historical data, advanced filtering',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q4 2026 (October-December)',
    category: 'Social',
    starRating: 5,
  },
  {
    id: 'real-world-integration',
    name: 'Real-World Integration',
    description: 'Gym partnerships, IRL events, territory battles, local competitions',
    status: 'Planned',
    priority: 'Low',
    timeline: 'Q4 2026 (October-December)',
    category: 'Innovation',
    starRating: 5,
  },
  {
    id: 'mobile-apps',
    name: 'Mobile Apps',
    description: 'Native iOS and Android apps with full feature parity',
    status: 'Planned',
    priority: 'Medium',
    timeline: 'Q4 2026 (October-December)',
    category: 'Core',
    starRating: 5,
  },
  {
    id: 'brand-evolution',
    name: 'Brand Evolution',
    description: 'Animated mascot, sound effects, enhanced visual identity',
    status: 'Planned',
    priority: 'Low',
    timeline: 'Q4 2026 (October-December)',
    category: 'Core',
    starRating: 5,
  },
];

export const innovationFeatures = roadmapFeatures.filter(f => f.starRating);
